Client -> CAS: authenticate
Client <- CAS: token
Client -> Drive: getUploadId
Client <- Drive: uploadId
Drive -> FileSystem: createUserSessionDir
Drive -> Mongo: saveFileMetadata
Client -> Drive: calculateChunks
Drive -> Mongo: chunkArray
Client -> Drive: saveFileChunk
Drive -> FileSystem: tempChunk
Drive -> Mongo: saveFileComplete
Client -> Drive: saveFileChunk
Drive -> FileSystem: tempChunk
Drive -> Mongo: saveFileComplete
Client -> Drive: saveFileChunk
Drive -> FileSystem: tempChunk
Drive -> Mongo: saveFileComplete
Client -> Drive: saveFileChunk
Drive -> FileSystem: tempChunk
Drive -> Mongo: saveFileComplete
Drive -> Drive: collateParts
Drive -> Drive: collateParts
Drive -> FileSystem: saveCompleteFile
Drive -> Mongo: updateFileStatus
Client <- Drive: saveFileComplete